"""Initial migration

Revision ID: 4fd70e44cd4a
Revises: 
Create Date: 2025-03-02 01:22:27.709776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd70e44cd4a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('price_eur', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('volume_24h', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crypto_prices_coin'), 'crypto_prices', ['coin'], unique=False)
    op.create_index(op.f('ix_crypto_prices_id'), 'crypto_prices', ['id'], unique=False)
    op.create_table('energy_consumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('power_usage', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('solar_generation', sa.Float(), nullable=True),
    sa.Column('grid_consumption', sa.Float(), nullable=True),
    sa.Column('is_predicted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_consumption_id'), 'energy_consumption', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('mining_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('gpu_config', sa.JSON(), nullable=True),
    sa.Column('coin', sa.String(), nullable=True),
    sa.Column('pool', sa.String(), nullable=True),
    sa.Column('wallet', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mining_configs_id'), 'mining_configs', ['id'], unique=False)
    op.create_index(op.f('ix_mining_configs_name'), 'mining_configs', ['name'], unique=False)
    op.create_table('mining_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('hashrate', sa.Float(), nullable=True),
    sa.Column('coin', sa.String(), nullable=True),
    sa.Column('earnings', sa.Float(), nullable=True),
    sa.Column('power_consumption', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('efficiency', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mining_stats_id'), 'mining_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mining_stats_id'), table_name='mining_stats')
    op.drop_table('mining_stats')
    op.drop_index(op.f('ix_mining_configs_name'), table_name='mining_configs')
    op.drop_index(op.f('ix_mining_configs_id'), table_name='mining_configs')
    op.drop_table('mining_configs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_energy_consumption_id'), table_name='energy_consumption')
    op.drop_table('energy_consumption')
    op.drop_index(op.f('ix_crypto_prices_id'), table_name='crypto_prices')
    op.drop_index(op.f('ix_crypto_prices_coin'), table_name='crypto_prices')
    op.drop_table('crypto_prices')
    # ### end Alembic commands ###
